/** ---------------------------------------- LICENSE SECTION -------------------------------------------------------------------
 *
 * Copyright (c) 2024 Piotr Wojtowicz
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * -----------------------------------------------------------------------------------------------------------------------------
 */

#ifndef IOTERM_CFG_H_
#define IOTERM_CFG_H_

#include "cfg.h"
#include "memconfig.h"

// defined on CMAKE level
//#define IOCMD_USE_OUT
//#define IOCMD_USE_LOG
//#define IOCMD_USE_IN
//#define IOCMD_USE_CMD

#define IOCMD_HEX_TO_BCD_DONT_USE_DIV           IOCMD_FEATURE_DISABLED
#define IOCMD_OUT_MINIMAL_PROGRAM_MEMORY_USAGE  IOCMD_FEATURE_ENABLED

#define IOCMD_SUPPORT_DATA_LOGGING              IOCMD_FEATURE_ENABLED
#define IOCMD_SUPPORT_DATA_COMPARISON           IOCMD_FEATURE_ENABLED
#define IOCMD_DATA_COMPARE_PRINT_BOTH_CONTEXTS  IOCMD_FEATURE_ENABLED
#define IOCMD_COMPARE_DATA_NUM_COLUMNS_TO_PRINT 2
//#define IOCMD_LOGS_TREE_OS_LOG_CONTEXT_SWITCH   IOCMD_FEATURE_DISABLED
#define IOCMD_OUT_SUPPORT_U64                   IOCMD_FEATURE_DISABLED

#define IOCMD_OUT_MINIMAL_STACK_USAGE           IOCMD_FEATURE_ENABLED
#define IOCMD_OUT_SUPPORT_POS_RETURNING         IOCMD_FEATURE_DISABLED


#define IOCMD_PROMOTION_INT8_TO_INT16           IOCMD_FEATURE_ENABLED
#define IOCMD_PROMOTION_INT16_TO_INT32          IOCMD_FEATURE_ENABLED

#define IOCMD_PROGRAM_MEMORY_BEGIN              APP_START
#define IOCMD_PROGRAM_MEMORY_END                APP_END

#define IOCMD_MAX_LOG_LENGTH                    128
#define IOCMD_MAX_ENTRANCE_LENGTH               48
#define IOCMD_MAX_LOG__DATA_1_LENGTH            1024
#define IOCMD_MAX_LOG__DATA_2_LENGTH            1024
// moved to memconfig.h
//#define IOCMD_LOG_MAIN_BUF_SIZE                 40000
#define IOCMD_LOG_QUIET_BUF_SIZE                0

#define IOCMD_LOGS_TREE_OS_CRITICAL_ID          IOCMD_OS_SWITCH

#define IOCMD_PROTECTION_LOCK(params)           OS_Enter_Critical_Section()
#define IOCMD_PROTECTION_UNLOCK(params)         OS_Exit_Critical_Section()
#define IOCMD_ENTER_CRITICAL()                  OS_Enter_Critical_Section()
#define IOCMD_EXIT_CRITICAL()                   OS_Exit_Critical_Section()

#define IOCMD_OS_GET_CURRENT_TIME()             OS_Get_Time()
#define IOCMD_OS_GET_CURRENT_CONTEXT_ID()       OS_Get_Current_Context_Id()
#define IOCMD_OS_GET_CURRENT_CONTEXT_TYPE()     OS_Get_Current_Context_Type()
#define IOCMD_OS_GET_CONTEXT_TYPE_NAME(type)    OS_Get_Context_Type_Name(type)
#define IOCMD_OS_GET_CONTEXT_NAME(type, id)     OS_Get_Context_Name(type, id)
#define IOCMD_OS_CONTEXT_TYPE_THREAD            OS_CONTEXT_TYPE_TASK

#define IOCMD_FILE_NAME_EXPECTED_MAX_SIZE       30


#define IOCMD_CONTEXT_ID_DT_EXTERNAL
typedef OS_Context_Id IOCMD_Context_ID_DT;


#define IOCMD_CONTEXT_TYPE_DT_EXTERNAL
//typedef OS_Context_Type_DT IOCMD_Context_Type_DT;
typedef uint8_t IOCMD_Context_Type_DT;



//#define IOCMD_LOG_PRINT_TIME      false
//#define IOCMD_LOG_PRINT_OS_CONTEXT  false



#define IOCMD_MACRO_COMPILATION_SWITCH_ENABLE      true


#define IOCMD_LOGS_TREE \
/*                   name                              compilation switch level   compilation switch entr    default level log           default silent level log   default entrances state    description */ \
IOCMD_LOG_ADD_MODULE(IOCMD_OS,                         IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "logs printed from FreeRTOS callbacks") \
IOCMD_LOG_ADD_GROUP( IOCMD_OS_SWITCH,                  IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "logs printed from FreeRTOS threads context switch routine") \
IOCMD_LOG_ADD_MODULE(MAIN_APP,                         IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , IOCMD_LOG_LEVEL_NOTICE    , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "logs printed from \"main\" function") \
IOCMD_LOG_ADD_ITEM(  MAIN_TASK_LED,                    IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "logs printed from LED task") \
IOCMD_LOG_ADD_ITEM(  MAIN_TASK_USART,                  IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , IOCMD_LOG_LEVEL_INFO_MID  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "logs printed from USART task") \
\
IOCMD_LOG_ADD_MODULE(USBD_DBG,                         IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - debug module") \
IOCMD_LOG_ADD_GROUP( USB_DBG_CDP,                      IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - configuration device parser") \
IOCMD_LOG_ADD_GROUP( USBD_DBG_INIT,                    IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - lib init") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_DEV_INIT,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - device init") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_DEV_ONOFF,               IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_INFO_HI    , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - device on/off switching") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_DEV_ONOFF_SOF_RECEIVED,  IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - device on/off switching - SOF_RECEIVED function") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_DEV_STATE,               IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - device state") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_DEV_INVALID_PARAMS,      IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - device invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IO_ONOFF,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - io on/off switching") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IO_STATE,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - io state") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IO_PROCESSING,           IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - io transfer processing") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IO_INVALID_PARAMS,       IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - io invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPEV_ONOFF,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp event-type on/off switching") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPEV_STATE,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp event-type state") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPEV_EVENT,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp event-type event for SOF") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPEV_PROCESSING,       IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp event-type transfer processing") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPEV_INVALID_PARAMS,   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - iotp event-type invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPBF_ONOFF,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp buff-type on/off switching") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPBF_STATE,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp buff-type state") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPBF_EVENT,            IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp buff-type event for SOF") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPBF_PROCESSING,       IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - iotp buff-type transfer processing") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_IOTPBF_INVALID_PARAMS,   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - iotp buff-type invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_EVENT_INIT,              IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - event init") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_EVENT_STATE,             IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - event state") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_EVENT_PROCESSING,        IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - event processing actions") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_EVENT_INVALID_PARAMS,    IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - event invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_REQ_INIT,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - request init") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_REQ_PROCESSING,          IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - request processing") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_REQ_INVALID_PARAMS,      IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_QUIET     , "USBD - request invalid parameters reporting") \
IOCMD_LOG_ADD_GROUP( USBD_DBG_USBDC,                   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - usbd configuration") \
IOCMD_LOG_ADD_GROUP( USBD_DBG_PORT,                    IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - pORT") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_INIT,               IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port init") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_DEV,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port device") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_IO,                 IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port io") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_IO_ONOFF,           IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port io on/off switching") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_EVENT,              IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port event") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_REQ,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port request") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_INVALID_PARAMS,     IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port invalid parameters reporting") \
IOCMD_LOG_ADD_ITEM(  USBD_DBG_PORT_IRQ,                IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - port interuptions") \
IOCMD_LOG_ADD_GROUP( CDC_VCOM,                         IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - Virtual COM Library") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_INIT,                    IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Virtual COM Library init") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_STATE,                   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Virtual COM Library state") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_ONOFF,                   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Virtual COM Library io on/off switching") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_EVENT,                   IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Virtual COM Library event") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_REQ,                     IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Virtual COM Library request") \
IOCMD_LOG_ADD_ITEM(  CDC_VCOM_INVALID_PARAMS,          IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Virtual COM Library invalid parameters reporting") \
IOCMD_LOG_ADD_GROUP( DFU,                              IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_WARN      , IOCMD_LOG_LEVEL_EMERG    , IOCMD_ENTRANCE_DISABLED  , "USBD - Device Firmware Upgrade") \
IOCMD_LOG_ADD_ITEM(  DFU_INIT,                         IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Device Firmware Upgrade init") \
IOCMD_LOG_ADD_ITEM(  DFU_STATE,                        IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Device Firmware Upgrade state") \
IOCMD_LOG_ADD_ITEM(  DFU_ONOFF,                        IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Device Firmware Upgrade io on/off switching") \
IOCMD_LOG_ADD_ITEM(  DFU_EVENT,                        IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Device Firmware Upgrade event") \
IOCMD_LOG_ADD_ITEM(  DFU_REQ,                          IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , "USBD - Device Firmware Upgrade request") \
IOCMD_LOG_ADD_ITEM(  DFU_INVALID_PARAMS,               IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_DISABLED  , IOCMD_LOG_LEVEL_DEBUG_LO  , IOCMD_LOG_LEVEL_DEBUG_LO , IOCMD_ENTRANCE_ENABLED   , "USBD - Device Firmware Upgrade invalid parameters reporting") \


#endif

